# prerequisite:
#   [install golangci-lint](https://golangci-lint.run/usage/install/#local-installation)
version: "2"
linters:
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
  disable:
    - gochecknoglobals # we allow global variables in packages
    - gochecknoinits # we allow inits in packages
    - goconst # we allow repeated values to go un-const'd
    - lll # we allow any line length
    - unparam # we allow function calls to name unused parameters
formatters:
  enable:
    - gofmt
    - goimports
